In [1]:
import pandas as pd
import numpy as np
from keras.layers import Dense, SimpleRNN, GRU , LSTM , Embedding
from keras.models  import Sequential

#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical

In [2]:
amz = pd.read_csv(r'D:\Datasets\amazonreviews.tsv', sep = '\t') 

In [3]:
amz.label.replace({'pos':1, 'neg':0}, inplace = True)
amz.tail()

label                                             review
9995      1  A revelation of life in small town America in ...
9996      1  Great biography of a very interesting journali...
9997      0  Interesting Subject; Poor Presentation: You'd ...
9998      0  Don't buy: The box looked used and it is obvio...
9999      1  Beautiful Pen and Fast Delivery.: The pen was ...

In [4]:
amz_x = amz.iloc[:, 1]
amz_y = amz.iloc[:, 0]
from sklearn.model_selection import train_test_split

x_train , x_test ,y_train , y_test = train_test_split(amz_x , amz_y , test_size = .2)

In [5]:
y_train = to_categorical(y_train)

In [6]:
y_train[3]

array([1., 0.], dtype=float32)

In [7]:
max_num_words = 10000
seq_len       = 50
embedding_size  = 100

from keras.preprocessing.text import Tokenizer  #  is used for tokinizeation
from keras.preprocessing.sequence import pad_sequences  # used to bring all samples to same length
#from keras.utils import to_categorical #  ( this function will be used to convert the labels to one hot encoding)
import numpy as np
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer(num_words = max_num_words)
tokenizer.fit_on_texts(amz.review)
x_train = tokenizer.texts_to_sequences(x_train) # will convert the text to sequences of IDs
x_train = pad_sequences(x_train , maxlen = seq_len)


x_test  =  tokenizer.texts_to_sequences(x_test)
x_test  =  pad_sequences(x_test , maxlen = seq_len)


model = Sequential()  # iniitialize the network
model.add(Embedding(input_dim = max_num_words,    # Embedding takes input in sequenses and gives output in embedings
                   input_length = seq_len,
                    output_dim = embedding_size))

In [8]:
model.add(LSTM(5)) 
model.add(Dense(2 , activation  = 'softmax'))  # this 2 bcoz u have 2 level in target variable
#from keras.optimizers import Adam
from tensorflow.keras.optimizers import Adam
adam = Adam(.001)
model.compile(optimizer= adam , loss = 'categorical_crossentropy' , metrics = ['accuracy'])

In [9]:
model.fit(x_train , y_train , epochs = 5 , batch_size= 32 , validation_split= .2)

Epoch 1/5
200/200 [==============================] - 6s 24ms/step - loss: 0.5938 - accuracy: 0.7041 - val_loss: 0.4678 - val_accuracy: 0.8100
Epoch 2/5
200/200 [==============================] - 3s 16ms/step - loss: 0.3547 - accuracy: 0.8687 - val_loss: 0.4229 - val_accuracy: 0.8188
Epoch 3/5
200/200 [==============================] - 3s 14ms/step - loss: 0.2302 - accuracy: 0.9236 - val_loss: 0.4611 - val_accuracy: 0.8106
Epoch 4/5
200/200 [==============================] - 3s 14ms/step - loss: 0.1541 - accuracy: 0.9517 - val_loss: 0.4945 - val_accuracy: 0.8100
Epoch 5/5
200/200 [==============================] - 3s 15ms/step - loss: 0.1148 - accuracy: 0.9658 - val_loss: 0.5336 - val_accuracy: 0.8056


In [10]:
pred = model.predict(x_test)
pred

array([[0.02115251, 0.97884756],
       [0.02909969, 0.97090036],
       [0.8990433 , 0.10095667],
       ...,
       [0.02797006, 0.97203   ],
       [0.983961  , 0.016039  ],
       [0.42353633, 0.57646376]], dtype=float32)

In [11]:
pred_classes = np.argmax(pred, axis=1)
pred_classes

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
cm = confusion_matrix(y_test, pred_classes )
cm

array([[799, 246],
       [183, 772]], dtype=int64)

In [14]:
accuracy = cm.diagonal().sum()/cm.sum()
accuracy

0.7855

# Dot Product

In [15]:
import pandas as pd
import numpy as np
import sklearn
import   scipy


In [16]:
A = [35 , 12 , 16 , 14]
B = [ 37 , 15 , 18 , 23]
C = [33 , 9 , 16  , 20]


In [17]:
DotAB = 35*37 + 12*15 + 18*16 + 23*14
DotAB

2085

In [18]:
DotAB = np.dot(A,B)
DotAB

2085

In [19]:
np.linalg.norm([A])

42.67317658670374

In [20]:
Cos_similarityAB = DotAB / (np.linalg.norm([A]) * np.linalg.norm([B]))
Cos_similarityAB

0.9877205776754668

In [21]:
import sklearn

In [22]:
sklearn.metrics.pairwise.cosine_similarity( [A], [B])

array([[0.98772058]])

In [23]:
if sklearn.metrics.pairwise.cosine_similarity( [A], [B]) > .99:
    print('high similarity')

In [24]:
type(amz_y)

pandas.core.series.Series

In [25]:
amz = pd.read_csv(r'D:\Datasets\amazonreviews.tsv', sep = '\t') 

In [26]:
amz.label.replace({'pos':1, 'neg':0}, inplace = True)
amz.tail()

label                                             review
9995      1  A revelation of life in small town America in ...
9996      1  Great biography of a very interesting journali...
9997      0  Interesting Subject; Poor Presentation: You'd ...
9998      0  Don't buy: The box looked used and it is obvio...
9999      1  Beautiful Pen and Fast Delivery.: The pen was ...

In [27]:
amz_x = amz.iloc[:, 1]
amz_y = amz.iloc[:, 0]
from sklearn.model_selection import train_test_split

x_train , x_test ,y_train , y_test = train_test_split(amz_x , amz_y , test_size = .2)

In [28]:
y_train = to_categorical(y_train)

In [29]:
max_num_words = 10000
seq_len       = 50
embedding_size  = 100

from keras.preprocessing.text import Tokenizer  #  is used for tokinizeation
from keras.preprocessing.sequence import pad_sequences  # used to bring all samples to same length
#from keras.utils import to_categorical #  ( this function will be used to convert the labels to one hot encoding)
import numpy as np
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer(num_words = max_num_words)
tokenizer.fit_on_texts(amz.review)
x_train = tokenizer.texts_to_sequences(x_train) # will convert the text to sequences of IDs
x_train = pad_sequences(x_train , maxlen = seq_len)


x_test  =  tokenizer.texts_to_sequences(x_test)
x_test  =  pad_sequences(x_test , maxlen = seq_len)

from keras.layers import Bidirectional
model = Sequential()  # iniitialize the network
model.add(Embedding(input_dim = max_num_words,    # Embedding takes input in sequenses and gives output in embedings
                   input_length = seq_len,
                    output_dim = embedding_size))

In [30]:
model.add(LSTM(5)) 
model.add(Dense(2 , activation  = 'softmax'))  # this 2 bcoz u have 2 level in target variable
#from keras.optimizers import Adam
from tensorflow.keras.optimizers import Adam
adam = Adam(.001)
model.compile(optimizer= adam , loss = 'categorical_crossentropy' , metrics = ['accuracy'])

In [31]:
model.fit(x_train , y_train , epochs = 5 , batch_size= 32 , validation_split= .2)

Epoch 1/5
200/200 [==============================] - 5s 18ms/step - loss: 0.5660 - accuracy: 0.7148 - val_loss: 0.4308 - val_accuracy: 0.8200
Epoch 2/5
200/200 [==============================] - 3s 14ms/step - loss: 0.3134 - accuracy: 0.8777 - val_loss: 0.4145 - val_accuracy: 0.8306
Epoch 3/5
200/200 [==============================] - 3s 14ms/step - loss: 0.1714 - accuracy: 0.9438 - val_loss: 0.4559 - val_accuracy: 0.8100
Epoch 4/5
200/200 [==============================] - 3s 15ms/step - loss: 0.1028 - accuracy: 0.9689 - val_loss: 0.5342 - val_accuracy: 0.8138
Epoch 5/5
200/200 [==============================] - 3s 15ms/step - loss: 0.0703 - accuracy: 0.9798 - val_loss: 0.6542 - val_accuracy: 0.8000


In [32]:
pred = model.predict(x_test)
pred

array([[0.01277241, 0.98722756],
       [0.01168243, 0.98831755],
       [0.03519462, 0.9648053 ],
       ...,
       [0.9858181 , 0.01418187],
       [0.01779462, 0.98220545],
       [0.98988837, 0.01011167]], dtype=float32)

In [33]:
pred_classes = np.argmax(pred, axis=1)
pred_classes

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)